<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ListarProveedores.aspx.cs" Inherits="Vistas.Admin.Proveedores.ListarProveedores" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="es">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            font-size: xx-large;
        }
        .auto-style4 {
            text-align: center;
        }
        .auto-style5 {
            height: 23px;
        }
        .auto-style7 {
            font-size: xx-large;
            background-color: #FFFFFF;
        }
        .auto-style8 {
            font-size: x-large;
        }
        .auto-style9 {
            text-align: right;
        }
    </style>
    <link rel="stylesheet" href="../../StyleSheetG6.css"/>
</head>
<body>
    <form id="form1" class="fontStyle" runat="server">
        <div>

            <table class="auto-style1">
                <tr>
                    <td>
                        <asp:HyperLink ID="hlVolverInicio" runat="server" NavigateUrl="~/Inicio.aspx">Volver al Menú Principal</asp:HyperLink>
                    </td>
                    <td class="auto-style9">
                        <asp:Label ID="lblCuentaIngresada" runat="server"></asp:Label>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2 mainItem"><strong>Proveedores</strong></td>
                    <td class="auto-style7"><strong><span class="subItem">Filtros de Búsqueda</span></strong></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style5"></td>
                    <td class="auto-style5"></td>
                </tr>
                <tr>
                    <td rowspan="11" class="auto-style4">
                        <asp:GridView ID="gvProveedores" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="IDProveedor" ForeColor="Black" GridLines="Vertical" AutoGenerateEditButton="True" OnPageIndexChanging="gvProveedores_PageIndexChanging" OnRowCancelingEdit="gvProveedores_RowCancelingEdit" OnRowDeleting="gvProveedores_RowDeleting" OnRowEditing="gvProveedores_RowEditing" OnRowUpdating="gvProveedores_RowUpdating" AutoGenerateDeleteButton="True">
                            <AlternatingRowStyle BackColor="White" />
                            <Columns>
                                <asp:TemplateField HeaderText="Id" InsertVisible="False" SortExpression="IDProveedor">
                                    <EditItemTemplate>
                                        <asp:Label ID="lbl_eit_Id" runat="server" Text='<%# Bind("IDProveedor") %>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_it_Id" runat="server" Text='<%# Bind("IDProveedor") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Nombre" SortExpression="NombreProveedor">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_eit_Nombre" runat="server" Text='<%# Bind("NombreProveedor") %>'></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="rfv_eit_Proveedor" runat="server" ControlToValidate="txt_eit_Nombre" ForeColor="Red">*</asp:RequiredFieldValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_it_Proveedor" runat="server" Text='<%# Bind("NombreProveedor") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Telefono" SortExpression="Telefono">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_eit_Telefono" runat="server" Text='<%# Bind("Telefono") %>' TextMode="Phone"></asp:TextBox>
                                        <asp:CompareValidator ID="cpv_eit_Telefono" runat="server" ControlToValidate="txt_eit_Telefono" ForeColor="Red" Operator="GreaterThan" Type="Integer" ValueToCompare="0">*</asp:CompareValidator>
                                        <asp:RequiredFieldValidator ID="rfv_eit_Telefono" runat="server" ControlToValidate="txt_eit_Telefono" ForeColor="Red">*</asp:RequiredFieldValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_it_Telefono" runat="server" Text='<%# Bind("Telefono") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Email" SortExpression="EMail">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_eit_Email" runat="server" Text='<%# Bind("EMail") %>'></asp:TextBox>
                                        <asp:RegularExpressionValidator ID="rev_eit_Email" runat="server" ControlToValidate="txt_eit_Email" ForeColor="Red" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*">*</asp:RegularExpressionValidator>
                                        <asp:RequiredFieldValidator ID="rfv_eit_Email" runat="server" ControlToValidate="txt_eit_Email" ForeColor="Red">*</asp:RequiredFieldValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_it_Email" runat="server" Text='<%# Bind("EMail") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Direccion" SortExpression="Direccion">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_eit_Direccion" runat="server" Text='<%# Bind("Direccion") %>'></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="rfv_eit_Direccion" runat="server" ControlToValidate="txt_eit_Direccion" ForeColor="Red">*</asp:RequiredFieldValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_it_Direccion" runat="server" Text='<%# Bind("Direccion") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Ciudad" SortExpression="NombreCiudad">
                                    <EditItemTemplate>
                                        <asp:DropDownList ID="ddl_eit_Ciudad" runat="server">
                                        </asp:DropDownList>
                                        <asp:Label ID="lbl_eit_CodigoCiudad" runat="server" Text='<%# Eval("CodigoCiudad") %>' Visible="False"></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_it_Ciudad" runat="server" Text='<%# Bind("NombreCiudad") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Estado" SortExpression="Estado">
                                    <EditItemTemplate>
                                        <asp:CheckBox ID="chk_eit_Estado" runat="server" Checked='<%# Bind("Estado") %>' Enabled="false" />
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:CheckBox ID="chk_it_Estado" runat="server" Checked='<%# Bind("Estado") %>' Enabled="false" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                            <EmptyDataTemplate>
                                <strong><em>No existen proveedores con los criterios de búsqueda propuestos</em></strong>
                            </EmptyDataTemplate>
                            <FooterStyle BackColor="#CCCC99" />
                            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                            <RowStyle BackColor="#F7F7DE" />
                            <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#FBFBF2" />
                            <SortedAscendingHeaderStyle BackColor="#848384" />
                            <SortedDescendingCellStyle BackColor="#EAEAD3" />
                            <SortedDescendingHeaderStyle BackColor="#575357" />
                        </asp:GridView>
                    </td>
                    <td class="auto-style8"><strong>ID Proveedor</strong></td>
                </tr>
                <tr>
                    <td>
                        <asp:TextBox ID="txtIdProveedor" runat="server"></asp:TextBox>
                        <asp:CompareValidator runat="server" ControlToValidate="txtIdProveedor" Operator="GreaterThan" Type="Integer" ValueToCompare="0" ID="cpvIdProveedor" ForeColor="Red">*</asp:CompareValidator>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style8"><strong>Nombre</strong></td>
                </tr>
                <tr>
                    <td>
                        <asp:TextBox ID="txtNombreProveedor" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style8"><strong>Ciudad</strong></td>
                </tr>
                <tr>
                    <td>
                        <asp:DropDownList ID="ddlFiltroCiudad" runat="server" AppendDataBoundItems="True">
                            <asp:ListItem>-- Seleccione --</asp:ListItem>
                        </asp:DropDownList>
                    </td>
                </tr>
                <tr>
                    <td>
                        &nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <asp:Button ID="btnFiltrar" class="myButton" runat="server" OnClick="btnFiltrar_Click" Text="Filtrar" />
                    </td>
                </tr>
                <tr>
                    <td>
                        &nbsp;</td>
                </tr>
            </table>

        </div>
    </form>
</body>
</html>
